# Generated by Django 3.0.5 on 2022-05-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20220506_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='comment',
            name='topping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Topping'),
            preserve_default=False,
        ),
    ]
