# Generated by Django 3.0.5 on 2022-05-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20220506_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField()),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.Topping')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
